//! CONFLICT_CONTINUE + CONFLICT_ABORT + NESTED_CONFLICT scenario buckets — generated by generate_matrix.py tooling.
//!
//! One #[test] per (family x observation x repeat) bucket. Each bucket runs
//! its scenarios through gt_sim::run_scenario and reports every violation in
//! a single panic, prefixed with stable scenario IDs for triage. See PLAN.md.

use super::gt_sim;
use super::scenario;

fn run_bucket(family: &str, observation: &str, repeat: &str) {
    let scenarios: Vec<_> = scenario::family(family)
        .into_iter()
        .filter(|s| s.observation == observation && s.repeat == repeat)
        .collect();
    assert!(
        !scenarios.is_empty(),
        "empty bucket {family}/{observation}/{repeat}"
    );
    let mut violations = Vec::new();
    for s in &scenarios {
        violations.extend(gt_sim::run_scenario(s));
    }
    assert!(
        violations.is_empty(),
        "{} attribution violations in {} {}/{} ({} scenarios):\n{}",
        violations.len(),
        family,
        observation,
        repeat,
        scenarios.len(),
        violations.join("\n")
    );
}

#[test]
fn conflict_continue_blind_once() {
    run_bucket("CONFLICT_CONTINUE", "blind", "once");
}

#[test]
fn conflict_continue_traced_once() {
    run_bucket("CONFLICT_CONTINUE", "traced", "once");
}

#[test]
fn conflict_abort_blind_once() {
    run_bucket("CONFLICT_ABORT", "blind", "once");
}

#[test]
fn conflict_abort_traced_once() {
    run_bucket("CONFLICT_ABORT", "traced", "once");
}

#[test]
fn nested_conflict_blind_once() {
    run_bucket("NESTED_CONFLICT", "blind", "once");
}

#[test]
fn nested_conflict_traced_once() {
    run_bucket("NESTED_CONFLICT", "traced", "once");
}
