//! LIFECYCLE scenario buckets — generated by generate_matrix.py tooling.
//!
//! One #[test] per (family x observation x repeat) bucket. Each bucket runs
//! its scenarios through gt_sim::run_scenario and reports every violation in
//! a single panic, prefixed with stable scenario IDs for triage. See PLAN.md.

use super::gt_sim;
use super::scenario;

fn run_bucket(family: &str, observation: &str, repeat: &str) {
    let scenarios: Vec<_> = scenario::family(family)
        .into_iter()
        .filter(|s| s.observation == observation && s.repeat == repeat)
        .collect();
    assert!(
        !scenarios.is_empty(),
        "empty bucket {family}/{observation}/{repeat}"
    );
    let mut violations = Vec::new();
    for s in &scenarios {
        violations.extend(gt_sim::run_scenario(s));
    }
    assert!(
        violations.is_empty(),
        "{} attribution violations in {} {}/{} ({} scenarios):\n{}",
        violations.len(),
        family,
        observation,
        repeat,
        scenarios.len(),
        violations.join("\n")
    );
}

#[test]
fn lifecycle_blind_once() {
    run_bucket("LIFECYCLE", "blind", "once");
}

#[test]
fn lifecycle_blind_twice() {
    run_bucket("LIFECYCLE", "blind", "twice");
}

#[test]
fn lifecycle_traced_once() {
    run_bucket("LIFECYCLE", "traced", "once");
}

#[test]
fn lifecycle_traced_twice() {
    run_bucket("LIFECYCLE", "traced", "twice");
}
