//! Scenario manifest for the Graphite workflow attribution suite.
//!
//! `scenarios.json` is generated by `generate_matrix.py` (the single source of
//! truth; IDs are stable and append-only) and embedded at compile time. See
//! `PLAN.md` in this directory for the full design.

use serde::Deserialize;
use std::str::FromStr;

/// One row of the scenario matrix. Dimension fields keep their raw manifest
/// strings; use the typed accessors (`stack_shape()`, `attribution_kind()`,
/// ...) when dispatching behavior.
#[derive(Debug, Clone, Deserialize)]
pub struct Scenario {
    pub id: String,
    pub family: String,
    pub stack: String,
    pub attribution: String,
    pub trunk: String,
    pub observation: String,
    pub repeat: String,
}

macro_rules! scenario_dimension {
    ($name:ident { $($variant:ident => $text:literal),+ $(,)? }) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        pub enum $name {
            $($variant),+
        }

        impl FromStr for $name {
            type Err = String;

            fn from_str(value: &str) -> Result<Self, Self::Err> {
                match value {
                    $($text => Ok(Self::$variant),)+
                    other => Err(format!(
                        "unknown {} value: {:?}",
                        stringify!($name),
                        other
                    )),
                }
            }
        }
    };
}

scenario_dimension!(StackShape {
    Single => "single",
    Stack2Bot => "stack2_bot",
    Stack2Top => "stack2_top",
    Stack3Mid => "stack3_mid",
    Stack3All => "stack3_all",
});

scenario_dimension!(Attribution {
    Committed => "committed",
    Uncommitted => "uncommitted",
    Mixed => "mixed",
    Multifile => "multifile",
});

scenario_dimension!(TrunkState {
    Ff => "ff",
    Diverged => "diverged",
    Overlap => "overlap",
});

scenario_dimension!(Observation {
    Traced => "traced",
    Blind => "blind",
});

scenario_dimension!(Repeat {
    Once => "once",
    Twice => "twice",
});

impl Repeat {
    pub fn rounds(self) -> usize {
        match self {
            Repeat::Once => 1,
            Repeat::Twice => 2,
        }
    }
}

impl Scenario {
    fn parse_dimension<T: FromStr<Err = String>>(&self, value: &str) -> T {
        value
            .parse()
            .unwrap_or_else(|error| panic!("{}: {}", self.id, error))
    }

    pub fn stack_shape(&self) -> StackShape {
        self.parse_dimension(&self.stack)
    }

    pub fn attribution_kind(&self) -> Attribution {
        self.parse_dimension(&self.attribution)
    }

    pub fn trunk_state(&self) -> TrunkState {
        self.parse_dimension(&self.trunk)
    }

    pub fn observation_mode(&self) -> Observation {
        self.parse_dimension(&self.observation)
    }

    pub fn repeat_mode(&self) -> Repeat {
        self.parse_dimension(&self.repeat)
    }
}

#[derive(Deserialize)]
struct Manifest {
    scenarios: Vec<Scenario>,
}

/// All 540 scenarios, in manifest order.
pub fn all_scenarios() -> Vec<Scenario> {
    let manifest: Manifest = serde_json::from_str(include_str!("scenarios.json"))
        .expect("scenarios.json should deserialize");
    manifest.scenarios
}

/// Every scenario of one family (e.g. `"SYNC_RESTACK"`), for family test files.
pub fn family(family: &str) -> Vec<Scenario> {
    let scenarios: Vec<Scenario> = all_scenarios()
        .into_iter()
        .filter(|scenario| scenario.family == family)
        .collect();
    assert!(!scenarios.is_empty(), "unknown scenario family: {family}");
    scenarios
}

/// Look up a single scenario by its stable ID (e.g. `"GT-SYNC_RESTACK-001"`).
pub fn by_id(id: &str) -> Scenario {
    all_scenarios()
        .into_iter()
        .find(|scenario| scenario.id == id)
        .unwrap_or_else(|| panic!("scenario {id} not found in scenarios.json"))
}
