//! WORKTREE + RENAME + MERGE_IN_STACK + PARTIAL_STAGE scenario buckets — generated by generate_matrix.py tooling.
//!
//! One #[test] per (family x observation x repeat) bucket. Each bucket runs
//! its scenarios through gt_sim::run_scenario and reports every violation in
//! a single panic, prefixed with stable scenario IDs for triage. See PLAN.md.

use super::gt_sim;
use super::scenario;

fn run_bucket(family: &str, observation: &str, repeat: &str) {
    let scenarios: Vec<_> = scenario::family(family)
        .into_iter()
        .filter(|s| s.observation == observation && s.repeat == repeat)
        .collect();
    assert!(
        !scenarios.is_empty(),
        "empty bucket {family}/{observation}/{repeat}"
    );
    let mut violations = Vec::new();
    for s in &scenarios {
        violations.extend(gt_sim::run_scenario(s));
    }
    assert!(
        violations.is_empty(),
        "{} attribution violations in {} {}/{} ({} scenarios):\n{}",
        violations.len(),
        family,
        observation,
        repeat,
        scenarios.len(),
        violations.join("\n")
    );
}

#[test]
fn worktree_blind_once() {
    run_bucket("WORKTREE", "blind", "once");
}

#[test]
fn worktree_traced_once() {
    run_bucket("WORKTREE", "traced", "once");
}

#[test]
fn rename_blind_once() {
    run_bucket("RENAME", "blind", "once");
}

#[test]
fn rename_traced_once() {
    run_bucket("RENAME", "traced", "once");
}

#[test]
fn merge_in_stack_blind_once() {
    run_bucket("MERGE_IN_STACK", "blind", "once");
}

#[test]
fn merge_in_stack_traced_once() {
    run_bucket("MERGE_IN_STACK", "traced", "once");
}

#[test]
fn partial_stage_blind_once() {
    run_bucket("PARTIAL_STAGE", "blind", "once");
}

#[test]
fn partial_stage_traced_once() {
    run_bucket("PARTIAL_STAGE", "traced", "once");
}
